version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: npm
    directories: [/ts, /examples/notes]
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /scripts/static-linux-arm64
    schedule:
      interval: weekly
