/**
 * GENERATED by scripts/generate-law-scale.ts — DO NOT hand-edit; regenerate.
 *
 * The primer-scale law-typing fixture (PRD-K4's scale bar): 40 relations
 * (8 closed + 32 ordinary), 200 field slots, 123 statements inline in one
 * schema() call. Its very compilation is the probe: the type-level class
 * machinery must carry this shape under default tsc limits, and the pins
 * at the bottom prove the map COMPUTED (never silently widened).
 */

import { closed } from "#closed.ts"
import { atMost } from "#count.ts"
import { on } from "#face.ts"
import { i64, interval, str, u64 } from "#fields.ts"
import { relation } from "#relation.ts"
import { schema } from "#schema.ts"
import { contained, mirrors, window } from "#statements.ts"

/** The identity-strength equality probe (the standard dual-function trick). */
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false

const Vocab0 = closed("Vocab0", ["Alpha0", "Beta0"])
const Vocab1 = closed("Vocab1", ["Alpha1", "Beta1"])
const Vocab2 = closed("Vocab2", ["Alpha2", "Beta2"])
const Vocab3 = closed("Vocab3", ["Alpha3", "Beta3"])
const Vocab4 = closed("Vocab4", ["Alpha4", "Beta4"])
const Vocab5 = closed("Vocab5", ["Alpha5", "Beta5"])
const Vocab6 = closed("Vocab6", ["Alpha6", "Beta6"])
const Vocab7 = closed("Vocab7", ["Alpha7", "Beta7"])

const R0 = relation("R0", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R1 = relation("R1", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R2 = relation("R2", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R3 = relation("R3", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R4 = relation("R4", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R5 = relation("R5", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R6 = relation("R6", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R7 = relation("R7", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R8 = relation("R8", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R9 = relation("R9", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R10 = relation("R10", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R11 = relation("R11", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R12 = relation("R12", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R13 = relation("R13", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R14 = relation("R14", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R15 = relation("R15", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R16 = relation("R16", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R17 = relation("R17", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R18 = relation("R18", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R19 = relation("R19", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R20 = relation("R20", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R21 = relation("R21", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R22 = relation("R22", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R23 = relation("R23", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R24 = relation("R24", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R25 = relation("R25", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R26 = relation("R26", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R27 = relation("R27", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R28 = relation("R28", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R29 = relation("R29", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R30 = relation("R30", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })
const R31 = relation("R31", { id: u64.fresh, ref: u64, kind: u64, at: interval(u64), label: str, score: i64 })

const LawScale = schema(
	"LawScale",
	{
		Vocab0,
		Vocab1,
		Vocab2,
		Vocab3,
		Vocab4,
		Vocab5,
		Vocab6,
		Vocab7,
		R0,
		R1,
		R2,
		R3,
		R4,
		R5,
		R6,
		R7,
		R8,
		R9,
		R10,
		R11,
		R12,
		R13,
		R14,
		R15,
		R16,
		R17,
		R18,
		R19,
		R20,
		R21,
		R22,
		R23,
		R24,
		R25,
		R26,
		R27,
		R28,
		R29,
		R30,
		R31
	},
	[
		contained(on(R1, "ref"), on(R0, "id")),
		contained(on(R2, "ref"), on(R1, "id")),
		contained(on(R3, "ref"), on(R2, "id")),
		contained(on(R4, "ref"), on(R3, "id")),
		contained(on(R5, "ref"), on(R4, "id")),
		contained(on(R6, "ref"), on(R5, "id")),
		contained(on(R7, "ref"), on(R6, "id")),
		contained(on(R8, "ref"), on(R7, "id")),
		contained(on(R9, "ref"), on(R8, "id")),
		contained(on(R10, "ref"), on(R9, "id")),
		contained(on(R11, "ref"), on(R10, "id")),
		contained(on(R12, "ref"), on(R11, "id")),
		contained(on(R13, "ref"), on(R12, "id")),
		contained(on(R14, "ref"), on(R13, "id")),
		contained(on(R15, "ref"), on(R14, "id")),
		contained(on(R16, "ref"), on(R15, "id")),
		contained(on(R17, "ref"), on(R16, "id")),
		contained(on(R18, "ref"), on(R17, "id")),
		contained(on(R19, "ref"), on(R18, "id")),
		contained(on(R20, "ref"), on(R19, "id")),
		contained(on(R21, "ref"), on(R20, "id")),
		contained(on(R22, "ref"), on(R21, "id")),
		contained(on(R23, "ref"), on(R22, "id")),
		contained(on(R24, "ref"), on(R23, "id")),
		contained(on(R25, "ref"), on(R24, "id")),
		contained(on(R26, "ref"), on(R25, "id")),
		contained(on(R27, "ref"), on(R26, "id")),
		contained(on(R28, "ref"), on(R27, "id")),
		contained(on(R29, "ref"), on(R28, "id")),
		contained(on(R30, "ref"), on(R29, "id")),
		contained(on(R31, "ref"), on(R30, "id")),
		contained(on(R0, "kind"), on(Vocab0, "id")),
		contained(on(R1, "kind"), on(Vocab1, "id")),
		contained(on(R2, "kind"), on(Vocab2, "id")),
		contained(on(R3, "kind"), on(Vocab3, "id")),
		contained(on(R4, "kind"), on(Vocab4, "id")),
		contained(on(R5, "kind"), on(Vocab5, "id")),
		contained(on(R6, "kind"), on(Vocab6, "id")),
		contained(on(R7, "kind"), on(Vocab7, "id")),
		contained(on(R8, "kind"), on(Vocab0, "id")),
		contained(on(R9, "kind"), on(Vocab1, "id")),
		contained(on(R10, "kind"), on(Vocab2, "id")),
		contained(on(R11, "kind"), on(Vocab3, "id")),
		contained(on(R12, "kind"), on(Vocab4, "id")),
		contained(on(R13, "kind"), on(Vocab5, "id")),
		contained(on(R14, "kind"), on(Vocab6, "id")),
		contained(on(R15, "kind"), on(Vocab7, "id")),
		contained(on(R16, "kind"), on(Vocab0, "id")),
		contained(on(R17, "kind"), on(Vocab1, "id")),
		contained(on(R18, "kind"), on(Vocab2, "id")),
		contained(on(R19, "kind"), on(Vocab3, "id")),
		contained(on(R20, "kind"), on(Vocab4, "id")),
		contained(on(R21, "kind"), on(Vocab5, "id")),
		contained(on(R22, "kind"), on(Vocab6, "id")),
		contained(on(R23, "kind"), on(Vocab7, "id")),
		contained(on(R24, "kind"), on(Vocab0, "id")),
		contained(on(R25, "kind"), on(Vocab1, "id")),
		contained(on(R26, "kind"), on(Vocab2, "id")),
		contained(on(R27, "kind"), on(Vocab3, "id")),
		contained(on(R28, "kind"), on(Vocab4, "id")),
		contained(on(R29, "kind"), on(Vocab5, "id")),
		contained(on(R30, "kind"), on(Vocab6, "id")),
		contained(on(R31, "kind"), on(Vocab7, "id")),
		window(on(R0, "id"), atMost(3n), on(R1, "ref")),
		window(on(R1, "id"), atMost(3n), on(R2, "ref")),
		window(on(R2, "id"), atMost(3n), on(R3, "ref")),
		window(on(R3, "id"), atMost(3n), on(R4, "ref")),
		window(on(R4, "id"), atMost(3n), on(R5, "ref")),
		window(on(R5, "id"), atMost(3n), on(R6, "ref")),
		window(on(R6, "id"), atMost(3n), on(R7, "ref")),
		window(on(R7, "id"), atMost(3n), on(R8, "ref")),
		window(on(R8, "id"), atMost(3n), on(R9, "ref")),
		window(on(R9, "id"), atMost(3n), on(R10, "ref")),
		window(on(R10, "id"), atMost(3n), on(R11, "ref")),
		window(on(R11, "id"), atMost(3n), on(R12, "ref")),
		window(on(R12, "id"), atMost(3n), on(R13, "ref")),
		window(on(R13, "id"), atMost(3n), on(R14, "ref")),
		window(on(R14, "id"), atMost(3n), on(R15, "ref")),
		window(on(R15, "id"), atMost(3n), on(R16, "ref")),
		window(on(R16, "id"), atMost(3n), on(R17, "ref")),
		window(on(R17, "id"), atMost(3n), on(R18, "ref")),
		window(on(R18, "id"), atMost(3n), on(R19, "ref")),
		window(on(R19, "id"), atMost(3n), on(R20, "ref")),
		mirrors(on(R0, "at"), on(R1, "at")),
		mirrors(on(R1, "at"), on(R2, "at")),
		mirrors(on(R2, "at"), on(R3, "at")),
		mirrors(on(R3, "at"), on(R4, "at")),
		mirrors(on(R4, "at"), on(R5, "at")),
		mirrors(on(R5, "at"), on(R6, "at")),
		mirrors(on(R6, "at"), on(R7, "at")),
		mirrors(on(R7, "at"), on(R8, "at")),
		mirrors(on(R8, "at"), on(R9, "at")),
		mirrors(on(R9, "at"), on(R10, "at")),
		mirrors(on(R10, "at"), on(R11, "at")),
		mirrors(on(R11, "at"), on(R12, "at")),
		mirrors(on(R12, "at"), on(R13, "at")),
		mirrors(on(R13, "at"), on(R14, "at")),
		mirrors(on(R14, "at"), on(R15, "at")),
		mirrors(on(R15, "at"), on(R16, "at")),
		mirrors(on(R16, "at"), on(R17, "at")),
		mirrors(on(R17, "at"), on(R18, "at")),
		mirrors(on(R18, "at"), on(R19, "at")),
		mirrors(on(R19, "at"), on(R20, "at")),
		contained(on(R21, ["ref", "at"]), on(R20, ["id", "at"])),
		contained(on(R22, ["ref", "at"]), on(R21, ["id", "at"])),
		contained(on(R23, ["ref", "at"]), on(R22, ["id", "at"])),
		contained(on(R24, ["ref", "at"]), on(R23, ["id", "at"])),
		contained(on(R25, ["ref", "at"]), on(R24, ["id", "at"])),
		contained(on(R26, ["ref", "at"]), on(R25, ["id", "at"])),
		contained(on(R27, ["ref", "at"]), on(R26, ["id", "at"])),
		contained(on(R28, ["ref", "at"]), on(R27, ["id", "at"])),
		contained(on(R29, ["ref", "at"]), on(R28, ["id", "at"])),
		contained(on(R30, ["ref", "at"]), on(R29, ["id", "at"])),
		contained(on(R31, ["ref", "at"]), on(R30, ["id", "at"])),
		contained(on(R0.where({ label: "hot" }), "id"), on(R0, "id")),
		contained(on(R1.where({ label: "hot" }), "id"), on(R1, "id")),
		contained(on(R2.where({ label: "hot" }), "id"), on(R2, "id")),
		contained(on(R3.where({ label: "hot" }), "id"), on(R3, "id")),
		contained(on(R4.where({ label: "hot" }), "id"), on(R4, "id")),
		contained(on(R5.where({ label: "hot" }), "id"), on(R5, "id")),
		contained(on(R6.where({ label: "hot" }), "id"), on(R6, "id")),
		contained(on(R7.where({ label: "hot" }), "id"), on(R7, "id")),
		contained(on(R8.where({ label: "hot" }), "id"), on(R8, "id"))
	]
)

// The machinery COMPUTED (never silently widened) — spot pins across the laws.
const pinChain: Equal<(typeof LawScale)["classes"]["R5"]["ref"], "R4.id"> = true
const pinVocab: Equal<(typeof LawScale)["classes"]["R9"]["kind"], "Vocab1.id"> = true
const pinGenerator: Equal<(typeof LawScale)["classes"]["R31"]["id"], "R31.id"> = true
const pinClosed: Equal<(typeof LawScale)["classes"]["Vocab7"]["id"], "Vocab7.id"> = true
const pinBare: Equal<(typeof LawScale)["classes"]["R3"]["score"], undefined> = true

export { LawScale, pinBare, pinChain, pinClosed, pinGenerator, pinVocab }
