[package]
name = "bumbledb"
version.workspace = true
edition = "2024"
publish = false

[features]
trace = []

alloc-counter = []

ground-off = []

[dependencies]
blake3 = "1"
bumbledb-macros = { path = "../bumbledb-macros" }

bumbledb-theory = { path = "../bumbledb-theory" }
heed = { version = "0.22", default-features = false } 

# On Apple platforms LMDB's default lock implementation is SysV semaphores,
[target.'cfg(target_os = "macos")'.dependencies]
heed = { version = "0.22", default-features = false, features = ["posix-sem"] }

[dev-dependencies]
heed = { version = "0.22", default-features = false }

[lints]
workspace = true
