/**
 * The successor error vocabulary. `LogError = DbError | ProtocolError` and
 * nothing else: a core failure crossing the log is the exact core `DbError`,
 * unchanged; `ProtocolError` adds only the log-specific reason roster from
 * `#codes.ts`, generated by the one native speller. Both classes are direct
 * Effect `Schema.TaggedError` values with a tagged reason; any displayed
 * `.code` is derived from the reason tag and there is no second mutable
 * classification authority. Terminal receipts are data in A, never errors.
 * After dispatch, submit/admin interruption is an `outcome-unknown` (or
 * decided) arm under the original identity; finalizer defects stay in `Cause`.
 */
import { dbError, DbError } from "@bjornpagen/bumbledb"
import { Schema } from "effect"
import { protocolErrorCodes } from "#codes.ts"

const Contention = Schema.Struct({
	_tag: Schema.Literal("Contention"),
	attempts: Schema.Number
})
const NotYetAvailable = Schema.Struct({
	_tag: Schema.Literal("NotYetAvailable"),
	requestedSeq: Schema.BigInt,
	capturedSeq: Schema.BigInt
})
const InsufficientLocalDisk = Schema.Struct({
	_tag: Schema.Literal("InsufficientLocalDisk"),
	requiredBytes: Schema.BigInt,
	availableBytes: Schema.BigInt
})
/** C08 envelope backpressure: the retained tail exceeded its policy. */
const MaintenanceRequired = Schema.Struct({
	_tag: Schema.Literal("MaintenanceRequired"),
	count: Schema.BigInt,
	bytes: Schema.BigInt
})
/**
 * The warm local materialization is behind the checkpoint base. Hydration is
 * NATIVE (recovery runs on the next history open / tenant acquire); `detail`
 * carries the native recovery/reopen guidance — this layer surfaces the
 * typed refusal and never repairs the cache itself.
 */
const MaterializationStale = Schema.Struct({
	_tag: Schema.Literal("MaterializationStale"),
	detail: Schema.String
})
const MigrationDrift = Schema.Struct({
	_tag: Schema.Literal("MigrationDrift"),
	detail: Schema.String
})
const MigrationUnsupported = Schema.Struct({
	_tag: Schema.Literal("MigrationUnsupported"),
	detail: Schema.String
})
const MigrationRepository = Schema.Struct({
	_tag: Schema.Literal("MigrationRepository"),
	path: Schema.String,
	detail: Schema.String
})
const MigrationIntentRequired = Schema.Struct({
	_tag: Schema.Literal("MigrationIntentRequired"),
	requirements: Schema.Array(
		Schema.Struct({
			code: Schema.Literals([
				"ambiguous",
				"destructive",
				"missing-backfill",
				"type-change",
				"unsupported",
				"stale-intent",
				"conflicting-intent"
			]),
			relation: Schema.String,
			field: Schema.NullOr(Schema.String),
			detail: Schema.String
		})
	),
	truncated: Schema.Boolean
})
const structured = [
	"Contention",
	"NotYetAvailable",
	"InsufficientLocalDisk",
	"MaintenanceRequired",
	"MaterializationStale",
	"MigrationDrift",
	"MigrationUnsupported",
	"MigrationRepository",
	"MigrationIntentRequired"
] as const
type StructuredTag = (typeof structured)[number]
type PlainTag = Exclude<(typeof protocolErrorCodes)[number], StructuredTag>
const PlainReason = Schema.Struct({
	_tag: Schema.Literals(
		protocolErrorCodes.filter(
			(code): code is PlainTag => !(structured as readonly string[]).includes(code)
		)
	)
})

export const ProtocolReason = Schema.Union([
	Contention,
	NotYetAvailable,
	InsufficientLocalDisk,
	MaintenanceRequired,
	MaterializationStale,
	MigrationDrift,
	MigrationUnsupported,
	MigrationRepository,
	MigrationIntentRequired,
	PlainReason
])
export type ProtocolReason = typeof ProtocolReason.Type

export class ProtocolError extends Schema.TaggedError<ProtocolError>()("ProtocolError", {
	operation: Schema.String,
	reason: ProtocolReason
}) {
	get code() {
		return this.reason._tag
	}
}

export type LogError = DbError | ProtocolError

/** The one wire error frame the native log machine throws across the bridge. */
const WireError = Schema.Union([
	Schema.Struct({ source: Schema.Literal("protocol"), reason: ProtocolReason }),
	Schema.Struct({ source: Schema.Literal("core"), reason: Schema.Unknown })
])
const decodeWireError = Schema.decodeUnknownOption(WireError)

/**
 * Decode a thrown bridge value into the typed union. Already-typed errors
 * pass through untouched (core errors are never rewrapped); an unrecognized
 * local throw is a core `Internal`, not a fabricated protocol outcome.
 */
export function logFailure(operation: string, cause: unknown): LogError {
	if (cause instanceof DbError || cause instanceof ProtocolError) {
		return cause
	}
	const wire = decodeWireError(cause)
	if (wire._tag === "Some") {
		if (wire.value.source === "protocol") {
			return new ProtocolError({ operation, reason: wire.value.reason })
		}
		return dbError(operation, wire.value.reason)
	}
	return dbError(operation, cause)
}

/** A plain-tag protocol failure, spelled once. */
export function protocolError(
	operation: string,
	code: Exclude<ProtocolReason["_tag"], (typeof structured)[number]>
): ProtocolError {
	return new ProtocolError({ operation, reason: { _tag: code } })
}

/** The boundary-parser refusal: malformed public input, before any I/O. */
export function invalidInput(operation: string): DbError {
	return new DbError({ operation, reason: { _tag: "InvalidArgument" } })
}

/** A closed/stale capability supplied dynamically. */
export function closedHandle(operation: string): DbError {
	return new DbError({ operation, reason: { _tag: "ClosedHandle" } })
}

/** Post-dispatch fiber interrupt: afterDispatch arm, same original identity. */
export function cancelled(operation: string): DbError {
	return new DbError({ operation, reason: { _tag: "Cancelled" } })
}
