//! The embedding surface: [`Db`], read frames and write transactions, the
//! typed write path, heap instances, and the host surface.
//!
//! The handle is `Send + Sync`; readers run concurrently on owned LMDB
//! snapshots; writes serialize on the store's one writer. A write
//! transaction is an in-memory net delta over the committed parent, judged
//! incrementally and committed once; an abort never wrote a fact.

use std::marker::PhantomData;
use std::sync::Arc;

use crate::error::Result;
use crate::image::cache::ImageCache;
use crate::schema::Schema;
#[cfg(test)]
use crate::work::WorkContext;
use bumbledb_theory::schema::{RelationId, StatementId};

mod builder;
mod collection;
mod get;
pub mod host;
mod maintain;
mod mutation;
mod open;
mod owned;
/// `schema!` expansion plumbing: the generated `Fact` impls call these.
/// Not API — no stability promises.
#[doc(hidden)]
pub mod plumbing;
mod read;
mod read_instance;
mod row_reader;
mod tx;
mod violations;

pub(crate) use violations::violations_from_judged;
mod write;

pub use builder::InstanceBuilder;
pub use collection::AcceptedCollection;
pub use mutation::MutationReport;
pub use owned::OwnedInstance;
pub(crate) use read_instance::ReadInstance;
pub use read_instance::{OwnedRead, ReadFrame};
pub use row_reader::RowReader;
pub use tx::WriteTx;
pub use write::{Committed, Witness, WriteOutcome};

/// One typed fact struct, as generated by the `schema!` macro.
///
/// The encode side appends the fact's canonical [`crate::Value`]s in sealed
/// field order — text and fixed bytes are owned by the value, there is no
/// dictionary and no intern id. The decode side reads a [`RowReader`] over
/// the stored canonical row bytes; `&'a str` / `&'a [u8]` fields borrow
/// directly from the storage snapshot's mapped pages (transaction-stable by
/// LMDB `CoW`) or a transaction's pending row bytes.
pub trait Fact<'a>: Sized {
    type Schema;

    const RELATION: RelationId;

    /// Append this fact's field values in sealed order.
    /// # Errors
    /// A value refused at the typed boundary (for example a fixed-width
    /// interval whose width is not the declared width).
    fn append_values(&self, out: &mut Vec<crate::Value>) -> Result<()>;

    /// Decode one stored canonical row.
    /// # Errors
    /// Corruption: the reader refuses malformed bytes.
    fn decode(row: RowReader<'a>) -> Result<Self>;
}

/// A typed key value: one key FD's determinant, carrying the relation's
/// fact type — `snap.get(key)` / `tx.get(key)` return `Option<Self::Fact>`.
/// Generated by `schema!` for every declared `R(x, ..) -> R` statement.
pub trait Key<'a>: Sized {
    type Schema;

    type Fact: Fact<'a, Schema = Self::Schema>;

    const STATEMENT: StatementId;

    /// Append the determinant values in projection order.
    /// # Errors
    /// A key value refused at the typed boundary.
    fn append_key_values(&self, out: &mut Vec<crate::Value>) -> Result<()>;
}

/// The database handle: the store owner plus the validated schema.
/// Shareable across threads (`Send + Sync`); dropping the last handle closes
/// the environment and releases the kernel directory lock.
/// `S` is the schema definition ([`crate::Theory`]) the database was
/// created/opened with — the typestate carried by [`WriteTx`],
/// [`OwnedRead`] / [`ReadFrame`] and [`crate::PreparedQuery`], so a fact or key of a
/// different schema is a compile error, not a runtime width check.
pub struct Db<S> {
    pub(crate) store: crate::storage::store::Store,
    schema: Arc<Schema>,
    /// The relation-image and text cache shared by every prepared program.
    cache: Arc<ImageCache>,
    marker: PhantomData<fn() -> S>,
}

impl<S> Db<S> {
    /// Clear cached query images and text. Live readers, prepared queries and
    /// results keep any storage they still own and remain valid. Later queries
    /// rebuild cache entries as needed; this does not change durable data.
    pub fn clear_cache(&self) {
        self.cache.clear();
    }

    #[must_use]
    pub fn schema(&self) -> &Schema {
        self.schema.as_ref()
    }
}

#[cfg(test)]
pub(crate) fn test_operation() -> WorkContext {
    WorkContext::new()
}

#[cfg(test)]
mod tests;
