//! The embedding surface (the 60-api doc, `docs/architecture/70-api.md`): [`Db`],
//! the read/write transaction closures, the typed write path, and export.
//!
//! Threading doctrine (`00-product.md`): the engine owns zero threads. The
//! handle is `Send + Sync`; readers run concurrently on LMDB snapshots;
//! writes queue on one mutex. A write transaction is a [`WriteDelta`]
//! — in-memory set arithmetic, nothing touches LMDB until commit, and an
//! abort (error or panic) never wrote anything.
//!
//! # The `Fact<'a>` lifetime (a decision, recorded here)
//!
//! Macro-generated fact structs borrow their variable-width fields
//! (`str` → `&'a str`, `bytes` → `&'a [u8]`), so the trait must express
//! "the struct is generic over a lifetime". Of the two shapes that can,
//! the **lifetime-parameterized trait** (`impl<'a> Fact<'a> for
//! Account<'a>`) wins over a GAT (`type Borrowed<'a>`): decode returns
//! plain `Self` at the resolver's lifetime with no projection type
//! anywhere, insert takes the struct at whatever lifetime the host holds
//! (an `Account<'b>` implements `Fact<'b>` — the encode paths read the
//! fields as borrows and force nothing toward `'static`), and
//! all-fixed-width structs implement `Fact<'a>` for every `'a` without
//! growing a lifetime themselves. A GAT would buy a lifetime-free trait
//! at the price of a second name for every struct (`F::Borrowed<'a>` next
//! to `F`) — an owned/borrowed twin in all but syntax, which the design
//! refuses. There are no owned twins and no modes: the borrowed struct is
//! the struct, and ownership is an explicit host act (`to_owned()` on the
//! field you keep).

use std::marker::PhantomData;
use std::sync::Mutex;

use crate::encoding::ValueRef;
use crate::error::Result;
use crate::image::cache::ImageCache;
use crate::schema::{FieldId, RelationId, Schema};
use crate::storage::delta::WriteDelta;
use crate::storage::env::{Environment, ReadTxn};

mod alloc;
mod delete;
mod delete_dyn;
mod encode_dyn;
mod get;
mod insert;
mod insert_dyn;
mod maintain;
mod open;
mod prepare;
mod read;
mod snapshot;
mod write;

/// Facts per write transaction in [`Db::bulk_load`] — the documented
/// chunking convenience (`40-storage.md`): large imports amortize commit
/// overhead without building one unbounded delta.
const BULK_CHUNK: usize = 4096;

/// One typed fact struct, as generated by the `schema!` macro. The write
/// side encodes against the delta (interning novel strings/bytes); the
/// read side encodes against the committed dictionary and reports a
/// never-interned value as "this fact cannot exist".
///
/// `'a` is the decode lifetime: variable-width fields (`&'a str` /
/// `&'a [u8]`) borrow from the resolver — the snapshot's committed
/// dictionary (mmap pages, txn-stable by LMDB `CoW`) or the write
/// transaction's pending interns (delta arena). A struct with no
/// variable-width field implements `Fact<'a>` for every `'a`. The trait
/// shape is a recorded decision — see the module doc.
pub trait Fact<'a>: Sized {
    /// The schema this struct belongs to — the `schema!` invocation's
    /// named unit struct. Write and read operations bound
    /// `F: Fact<'_, Schema = S>` against `Db<S>`, so a cross-schema fact
    /// is a compile error.
    type Schema;

    /// The relation this struct declares, by declaration order.
    const RELATION: RelationId;

    /// Encodes the canonical fact bytes against a write context, interning
    /// novel strings and bytes through the delta. Appends to `out`.
    ///
    /// # Errors
    ///
    /// Storage errors from the dictionary reads.
    fn encode_write(&self, tx: &mut WriteTx<'_, Self::Schema>, out: &mut Vec<u8>) -> Result<()>;

    /// Encodes for the delete path: pending intern ids first (so an
    /// insert-then-delete within one transaction cancels byte-exactly),
    /// then the committed dictionary — never minting. `Ok(false)` means a
    /// string or bytes value is known to neither: the fact provably
    /// cannot exist in base or delta, the delete is a no-op, and the
    /// dictionary stays untouched (`out` is left unusable in that case).
    ///
    /// # Errors
    ///
    /// Storage errors from the dictionary reads.
    fn encode_delete(&self, tx: &WriteTx<'_, Self::Schema>, out: &mut Vec<u8>) -> Result<bool>;

    /// Encodes against a read context. `Ok(false)` means a string or bytes
    /// value was never interned — the fact cannot exist in the database
    /// (`out` is left untouched in that case; otherwise appended).
    ///
    /// # Errors
    ///
    /// Storage errors from the dictionary reads.
    fn encode_read(&self, snap: &Snapshot<'_, Self::Schema>, out: &mut Vec<u8>) -> Result<bool>;

    /// Decodes canonical fact bytes back into the typed struct.
    /// Variable-width fields borrow from the snapshot's dictionary at
    /// `'a`; UTF-8 is validated at resolve (parse, don't validate) —
    /// without a copy.
    ///
    /// # Errors
    ///
    /// `Corruption` on undecodable bytes or dangling intern ids.
    fn decode(snap: &'a Snapshot<'_, Self::Schema>, fact: &[u8]) -> Result<Self>;

    /// Decodes canonical fact bytes inside a write transaction — the
    /// point-read sibling of [`Fact::decode`], resolving intern ids
    /// pending-first (a fact inserted this transaction carries provisional
    /// ids, borrowed from the delta arena) and through the committed
    /// dictionary otherwise.
    ///
    /// # Errors
    ///
    /// `Corruption` on undecodable bytes or dangling intern ids.
    fn decode_write(tx: &'a WriteTx<'_, Self::Schema>, fact: &[u8]) -> Result<Self>;
}

/// Generated alongside [`Fact`] for relations with **exactly one** fresh
/// field: names the newtype [`WriteTx::get`] accepts as the key. Relations
/// with zero or several key statements have no single dominant key, so
/// their point reads spell the statement out through [`WriteTx::get_dyn`]
/// (the multi-key typed shape is an open item, `docs/architecture/70-api.md`).
pub trait FreshKeyed<'a>: Fact<'a> {
    /// The fresh field's generated newtype.
    type FreshKey: Fresh;
}

/// A fresh-minted newtype, as generated by the `schema!` macro for a
/// `fresh` field declared `as NewType`: [`WriteTx::alloc`] mints the next
/// value with the field already known.
pub trait Fresh: Sized {
    /// The schema the newtype's relation belongs to — [`WriteTx::alloc`]
    /// bounds `T: Fresh<Schema = S>`, so minting through a foreign
    /// schema's newtype is a compile error (the same closure as
    /// [`Fact::Schema`]).
    type Schema;

    /// The relation owning the fresh field.
    const RELATION: RelationId;
    /// The fresh field itself.
    const FIELD: FieldId;
    /// Wraps a minted raw value.
    fn from_fresh(raw: u64) -> Self;
    /// The raw value back out — the encode side of [`WriteTx::get`]'s
    /// key lookup (fresh newtypes are `Copy`).
    fn fresh(self) -> u64;
}

/// The database handle: the LMDB environment, the image cache, and the
/// writer mutex. Shareable across threads (`Send + Sync`); dropping the
/// handle closes the environment.
///
/// `S` is the schema definition ([`crate::Theory`]) the database was
/// created or opened with — a phantom typestate threaded through
/// [`WriteTx`], [`Snapshot`], and [`crate::PreparedQuery`], so a fact or
/// prepared query of one schema cannot reach a database of another
/// (compile error, not a runtime width check). The validated
/// [`Schema`] itself is owned by the handle: `create`/`open` validate the
/// definition's descriptor and surface an invalid declaration as the
/// typed [`crate::error::SchemaError`].
///
/// Transaction closures return [`crate::Result`]; host code with its own
/// error type wraps the transaction instead of threading the type
/// through: run the closure for the engine work, then convert — a
/// generic error parameter here would force turbofish annotations on
/// every plain `Ok(())` closure.
pub struct Db<S> {
    env: Environment,
    cache: ImageCache,
    writer: Mutex<()>,
    /// The thread currently inside [`Db::write`] (0 = none): a nested
    /// `write` on the same thread would self-deadlock on the writer
    /// mutex forever, so it panics loudly instead.
    writer_thread: std::sync::atomic::AtomicU64,
    /// The reader cache: one parked LMDB read
    /// transaction, reused while no commit has intervened. Sound because
    /// this handle is the environment's ONLY writer (exclusive lock at
    /// open): if [`Db::commit_seq`] is unchanged since the parked
    /// snapshot began, the parked snapshot is bit-identical to a fresh
    /// one — and the per-read `mdb_txn_begin` (the point path's last
    /// fixed cost) is skipped entirely. Readers
    /// `try_lock`: contended readers fall back to a fresh transaction,
    /// never block.
    read_cache: Mutex<Option<ParkedReader>>,
    /// Commits since open (monotone; bumped only when a commit changed
    /// state). The parked reader's validity token.
    commit_seq: std::sync::atomic::AtomicU64,
    schema: Schema,
    /// The typestate marker (`fn() -> S` keeps `Send + Sync` independent
    /// of `S` — the definition value itself is consumed at open).
    marker: PhantomData<fn() -> S>,
}

impl<S> Db<S> {
    /// The LMDB environment (reader: `crate::verify_store` — the sweeper
    /// opens its own snapshot, and its fixture tests inject raw desyncs
    /// through the environment's write transactions).
    pub(crate) fn env(&self) -> &Environment {
        &self.env
    }

    /// The validated schema (reader: `crate::verify_store`).
    pub(crate) fn schema(&self) -> &Schema {
        &self.schema
    }
}

/// One parked read transaction and the commit sequence it saw.
struct ParkedReader {
    txn: heed::RoTxn<'static, heed::WithoutTls>,
    commit_seq: u64,
}

/// Clears the owner mark when the write closure exits — normally, by
/// error, or by unwind — so the next `write` on this thread proceeds.
struct WriterThreadReset<'a>(&'a std::sync::atomic::AtomicU64);

/// A failed [`Db::bulk_load`]: the underlying error plus the number of
/// facts committed by the complete chunks before it — every fact of a
/// committed chunk is durable; nothing of the failing chunk is.
#[derive(Debug)]
pub struct BulkLoadError {
    /// Facts that changed state in the chunks committed before the error.
    pub committed: u64,
    /// What stopped the import.
    pub error: crate::error::Error,
}

/// One consistent read snapshot: executes prepared queries and exports
/// relations. Handed to [`Db::read`] closures. Carries the handle's
/// schema typestate `S`, so a prepared query executes only against
/// snapshots of a same-schema database by construction.
pub struct Snapshot<'db, S> {
    txn: ReadTxn<'db>,
    cache: &'db ImageCache,
    schema: &'db Schema,
    marker: PhantomData<fn() -> S>,
}

impl<'db, S> Snapshot<'db, S> {
    /// The snapshot's read transaction (reader: the staleness signal —
    /// [`crate::PreparedQuery::staleness`] takes the snapshot directly
    /// rather than routing through a `Snapshot` wrapper method).
    pub(crate) fn txn(&self) -> &ReadTxn<'db> {
        &self.txn
    }
}

/// One write transaction: an in-memory write delta over a read view. Operations
/// are in-memory set arithmetic — order is semantically irrelevant, and
/// `delete(old); insert(new)` in either order is the blessed mutation
/// idiom. Handed to [`Db::write`] closures; offers no queries — point
/// reads only ([`WriteTx::contains`] / [`WriteTx::get`] /
/// [`WriteTx::get_dyn`]), which observe the final-state view the judgment
/// phase will judge. No prepared-query or snapshot type is reachable from
/// here (`docs/architecture/70-api.md`: full queries in write transactions
/// stay unrepresentable). Carries the handle's schema typestate `S`:
/// typed operations bound `F: Fact<'_, Schema = S>`.
pub struct WriteTx<'a, S> {
    view: ReadTxn<'a>,
    delta: WriteDelta<'a>,
    schema: &'a Schema,
    scratch: Vec<u8>,
    /// Reused per dynamic fact: `bulk_load` must not allocate a value
    /// buffer per imported row.
    refs: Vec<ValueRef>,
    marker: PhantomData<fn() -> S>,
}

impl<S> WriteTx<'_, S> {
    /// Runs `body` with the encode scratch taken out (a typed encode
    /// borrows the whole transaction mutably alongside the buffer),
    /// restoring the buffer — and its capacity — afterward, success or
    /// error. The one scratch discipline of every typed operation.
    fn with_scratch<R>(
        &mut self,
        body: impl FnOnce(&mut Self, &mut Vec<u8>) -> Result<R>,
    ) -> Result<R> {
        let mut bytes = std::mem::take(&mut self.scratch);
        bytes.clear();
        let out = body(self, &mut bytes);
        self.scratch = bytes;
        out
    }
}

/// How [`WriteTx::encode_dyn`] treats novel strings and bytes: the insert
/// path mints provisional intern ids; the delete path only resolves —
/// a value neither pending nor committed proves its fact absent.
#[derive(Clone, Copy, PartialEq, Eq)]
enum InternMode {
    Mint,
    Resolve,
}

/// `schema!` expansion plumbing: the generated `Fact` impls call these.
/// Not API — no stability promises; nothing here is reachable from the
/// documented surface.
#[doc(hidden)]
pub mod plumbing;

#[cfg(test)]
mod tests;

#[cfg(all(test, feature = "trace"))]
mod trace_tests;
