import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const RELATIONS = 32
const VOCABS = 8

function generate(): string {
	const lines: string[] = []
	lines.push("/**")
	lines.push(" * GENERATED by scripts/generate-law-scale.ts — DO NOT hand-edit; regenerate.")
	lines.push(" *")
	lines.push(" * The primer-scale law-typing fixture (PRD-K4's scale bar): 40 relations")
	lines.push(" * (8 closed + 32 ordinary), 200 field slots, 155 statements inline in one")
	lines.push(" * schema() call. Its very compilation is the probe: the type-level class")
	lines.push(" * machinery must carry this shape under default tsc limits, and the pins")
	lines.push(" * at the bottom prove the map COMPUTED (never silently widened).")
	lines.push(" */")
	lines.push("")
	lines.push('import { within } from "#capacity.ts"')
	lines.push('import { closed } from "#closed.ts"')
	lines.push('import { on } from "#face.ts"')
	lines.push('import { i64, interval, str, u64 } from "#fields.ts"')
	lines.push('import { relation } from "#relation.ts"')
	lines.push('import { schema } from "#schema.ts"')
	lines.push('import { capacity, contained, key, mirrors } from "#statements.ts"')
	lines.push("")
	lines.push("/** The identity-strength equality probe (the standard dual-function trick). */")
	lines.push("type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false")
	lines.push("")
	for (let v = 0; v < VOCABS; v += 1) {
		lines.push(`const Vocab${v} = closed("Vocab${v}", ["Alpha${v}", "Beta${v}"])`)
	}
	lines.push("")
	for (let i = 0; i < RELATIONS; i += 1) {

		lines.push(
			`const R${i} = relation("R${i}", { id: u64.fresh, ref: u64, kind: Vocab${i % VOCABS}.id, at: interval(u64), label: str, score: i64 })`
		)
	}
	lines.push("")
	const members: string[] = []
	for (let v = 0; v < VOCABS; v += 1) {
		members.push(`Vocab${v}`)
	}
	for (let i = 0; i < RELATIONS; i += 1) {
		members.push(`R${i}`)
	}
	const statements: string[] = []

	for (let i = 1; i < RELATIONS; i += 1) {
		statements.push(`contained(on(R${i}, "ref"), on(R${i - 1}, "id"))`)
	}

	for (let i = 0; i < RELATIONS; i += 1) {
		statements.push(`contained(on(R${i}, "kind"), on(Vocab${i % VOCABS}, "id"))`)
	}

	for (let i = 0; i < 20; i += 1) {
		statements.push(`capacity(on(R${i}, "id"), within(0n, 3n), on(R${i + 1}, "ref"))`)
	}

	for (let i = 0; i <= 20; i += 1) {
		statements.push(`key(R${i}, ["at"])`)
	}

	for (let i = 0; i < 20; i += 1) {
		statements.push(`mirrors(on(R${i}, "at"), on(R${i + 1}, "at"))`)
	}

	for (let i = 21; i < RELATIONS; i += 1) {
		statements.push(`key(R${i - 1}, ["id", "at"])`)
	}
	for (let i = 21; i < RELATIONS; i += 1) {
		statements.push(`contained(on(R${i}, ["ref", "at"]), on(R${i - 1}, ["id", "at"]))`)
	}

	for (let i = 0; i < 9; i += 1) {
		statements.push(`contained(on(R${i}.where({ label: "hot" }), "id"), on(R${i}, "id"))`)
	}
	lines.push(`const LawScale = schema("LawScale", { ${members.join(", ")} }, [`)
	lines.push(statements.map((statement) => `\t${statement}`).join(",\n"))
	lines.push("])")
	lines.push("")
	lines.push("// The machinery COMPUTED (never silently widened) — spot pins across the laws.")
	lines.push('const pinChain: Equal<(typeof LawScale)["classes"]["R5"]["ref"], "R4.id"> = true')
	lines.push('const pinVocab: Equal<(typeof LawScale)["classes"]["R9"]["kind"], "Vocab1.id"> = true')
	lines.push('const pinGenerator: Equal<(typeof LawScale)["classes"]["R31"]["id"], "R31.id"> = true')
	lines.push('const pinClosed: Equal<(typeof LawScale)["classes"]["Vocab7"]["id"], "Vocab7.id"> = true')
	lines.push('const pinBare: Equal<(typeof LawScale)["classes"]["R3"]["score"], undefined> = true')
	lines.push("")
	lines.push("export { LawScale, pinBare, pinChain, pinClosed, pinGenerator, pinVocab }")
	lines.push("")
	return lines.join("\n")
}

const outPath = path.join(fileURLToPath(new URL("..", import.meta.url)), "test", "fixtures", "law-scale.ts")
fs.writeFileSync(outPath, generate())
console.log(`law-scale fixture written: ${outPath}`)
