import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

/**
 * Regenerates `ts/test/fixtures/law-scale.ts` in the SUCCESSOR spelling:
 * fresh-less fields (plain `u64` ids), 32 DECLARED id keys at the head of
 * the statement list (keys are declared statements now — the fresh-implied
 * key authority is deleted), named-options `capacity(target, { from,
 * within })`, and the `pinNoGenerator` pin (an id in no law is BARE:
 * `classes[R31][id]` is `undefined`, never a self-generator).
 *
 * Emits the fixture's exact formatted shape (tab indentation, one member
 * and one statement per line) so regeneration is byte-stable without a
 * formatter pass. Run manually: `node scripts/generate-law-scale.ts`.
 */

const RELATIONS = 32
const VOCABS = 8

function generate(): string {
	const lines: string[] = []
	lines.push("/**")
	lines.push(" * GENERATED by scripts/generate-law-scale.ts — DO NOT hand-edit; regenerate.")
	lines.push(" *")
	lines.push(" * The primer-scale law-typing fixture (PRD-K4's scale bar): 40 relations")
	lines.push(" * (8 closed + 32 ordinary), 200 field slots, 187 statements inline in one")
	lines.push(" * schema() call. Its very compilation is the probe: the type-level class")
	lines.push(" * machinery must carry this shape under default tsc limits, and the pins")
	lines.push(" * at the bottom prove the map COMPUTED (never silently widened).")
	lines.push(" */")
	lines.push("")
	lines.push('import { within } from "#capacity.ts"')
	lines.push('import { closed } from "#closed.ts"')
	lines.push('import { on } from "#face.ts"')
	lines.push('import { i64, interval, str, u64 } from "#fields.ts"')
	lines.push('import { relation } from "#relation.ts"')
	lines.push('import { schema } from "#schema.ts"')
	lines.push('import { capacity, contained, key, mirrors } from "#statements.ts"')
	lines.push("")
	lines.push("/** The identity-strength equality probe (the standard dual-function trick). */")
	lines.push("type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false")
	lines.push("")
	for (let v = 0; v < VOCABS; v += 1) {
		lines.push(`const Vocab${v} = closed("Vocab${v}", ["Alpha${v}", "Beta${v}"])`)
	}
	lines.push("")
	for (let i = 0; i < RELATIONS; i += 1) {
		lines.push(
			`const R${i} = relation("R${i}", { id: u64, ref: u64, kind: Vocab${i % VOCABS}.id, at: interval(u64), label: str, score: i64 })`
		)
	}
	lines.push("")

	const members: string[] = []
	for (let v = 0; v < VOCABS; v += 1) {
		members.push(`Vocab${v}`)
	}
	for (let i = 0; i < RELATIONS; i += 1) {
		members.push(`R${i}`)
	}

	const statements: string[] = []

	// Declared primary keys: the successor spells every id key explicitly.
	for (let i = 0; i < RELATIONS; i += 1) {
		statements.push(`key(R${i}, ["id"])`)
	}

	for (let i = 1; i < RELATIONS; i += 1) {
		statements.push(`contained(on(R${i}, "ref"), on(R${i - 1}, "id"))`)
	}

	for (let i = 0; i < RELATIONS; i += 1) {
		statements.push(`contained(on(R${i}, "kind"), on(Vocab${i % VOCABS}, "id"))`)
	}

	for (let i = 0; i < 20; i += 1) {
		statements.push(`capacity(on(R${i}, "id"), { from: on(R${i + 1}, "ref"), within: within(0n, 3n) })`)
	}

	for (let i = 0; i <= 20; i += 1) {
		statements.push(`key(R${i}, ["at"])`)
	}

	for (let i = 0; i < 20; i += 1) {
		statements.push(`mirrors(on(R${i}, "at"), on(R${i + 1}, "at"))`)
	}

	for (let i = 21; i < RELATIONS; i += 1) {
		statements.push(`key(R${i - 1}, ["id", "at"])`)
	}
	for (let i = 21; i < RELATIONS; i += 1) {
		statements.push(`contained(on(R${i}, ["ref", "at"]), on(R${i - 1}, ["id", "at"]))`)
	}

	for (let i = 0; i < 9; i += 1) {
		statements.push(`contained(on(R${i}.where({ label: "hot" }), "id"), on(R${i}, "id"))`)
	}

	lines.push("const LawScale = schema(")
	lines.push('\t"LawScale",')
	lines.push("\t{")
	lines.push(members.map((member) => `\t\t${member}`).join(",\n"))
	lines.push("\t},")
	lines.push("\t[")
	lines.push(statements.map((statement) => `\t\t${statement}`).join(",\n"))
	lines.push("\t]")
	lines.push(")")
	lines.push("")
	lines.push("// The machinery COMPUTED (never silently widened) — spot pins across the laws.")
	lines.push('const pinChain: Equal<(typeof LawScale)["classes"]["R5"]["ref"], "R4.id"> = true')
	lines.push('const pinVocab: Equal<(typeof LawScale)["classes"]["R9"]["kind"], "Vocab1.id"> = true')
	lines.push("// The generator authority is deleted with fresh: an id in no law is BARE.")
	lines.push('const pinNoGenerator: Equal<(typeof LawScale)["classes"]["R31"]["id"], undefined> = true')
	lines.push('const pinClosed: Equal<(typeof LawScale)["classes"]["Vocab7"]["id"], "Vocab7.id"> = true')
	lines.push('const pinBare: Equal<(typeof LawScale)["classes"]["R3"]["score"], undefined> = true')
	lines.push("")
	lines.push("export { LawScale, pinBare, pinChain, pinClosed, pinNoGenerator, pinVocab }")
	lines.push("")
	return lines.join("\n")
}

const outPath = path.join(fileURLToPath(new URL("..", import.meta.url)), "test", "fixtures", "law-scale.ts")
fs.writeFileSync(outPath, generate())
console.log(`law-scale fixture written: ${outPath}`)
