import Bumbledb.Conformance

/-!
# Literal F64 query boundary checks

These hand-written inputs and answers pass through the real JSON parser,
typed-value decoder, query evaluator, grouping and canonical comparison.
Neither payloads nor expected answers are generated by Rust's float/key code.
The seeded corpus remains the generated three-way lane; these boundary
checks deliberately survive changes to its random query distribution.
-/

namespace Bumbledb.Conformance.F64Boundary

private def row (payload : String) : String := "[{\"f64\":\"" ++ payload ++ "\"}]"

private def rows (payloads : List String) : String :=
  "[" ++ String.intercalate "," (payloads.map row) ++ "]"

private def boundaries : List String :=
  ["fff0000000000000", "ffefffffffffffff", "bff0000000000000", "8000000000000001",
   "0000000000000000", "0000000000000001", "000fffffffffffff", "0010000000000000",
   "3ff0000000000000", "3ff0000000000001", "7fefffffffffffff", "7ff0000000000000",
   "7ff8000000000000"]

private def literal (payload : String) : String := "{\"lit\":{\"f64\":\"" ++ payload ++ "\"}}"

private def cmp (op rhs : String) : String :=
  "{\"cmp\":{\"op\":\"" ++ op ++ "\",\"lhs\":{\"var\":0},\"rhs\":" ++ rhs ++ "}}"

private def document (finds conditions params expected : String)
    (binding : String := "{\"var\":0}") : String :=
  "{\"theory\":{\"relations\":[{\"id\":0,\"fields\":[\"f64\"]}],\"ground_axioms\":[]}," ++
  "\"instance\":[{\"relation\":0,\"facts\":" ++
    rows (boundaries ++ ["7ff8000000000000"]) ++ "}]," ++
  "\"query\":{\"cq\":{\"interiors\":[],\"head\":[{}],\"rules\":[{" ++
    "\"finds\":" ++ finds ++ ",\"atoms\":[{\"edb\":0,\"bindings\":[[0," ++ binding ++ "]]}]," ++
    "\"negated\":[],\"conditions\":[" ++ conditions ++ "]}]}}," ++
  "\"params\":" ++ params ++ ",\"answers\":" ++ expected ++ "}"

private def agrees (text : String) : Bool :=
  match checkCase text with
  | .ok none => true
  | _ => false

private def project (conditions : String) (expected : List String) : Bool :=
  agrees (document "[{\"var\":0}]" conditions "[]" (rows expected))

-- Projection is set-valued even though the source lists canonical NaN twice.
#guard project "" boundaries

-- Canonical NaN is reflexively equal and strictly above positive infinity.
#guard project (cmp "eq" (literal "7ff8000000000000")) ["7ff8000000000000"]
#guard project (cmp "gt" (literal "7ff0000000000000")) ["7ff8000000000000"]
#guard project (cmp "ne" "{\"var\":0}") []

-- Signs, both infinities, neighboring subnormal/normal values, neighboring 1s.
#guard project (cmp "lt" (literal "0000000000000000"))
  ["fff0000000000000", "ffefffffffffffff", "bff0000000000000", "8000000000000001"]
#guard project (cmp "ge" (literal "0000000000000001") ++ "," ++
    cmp "le" (literal "0010000000000000"))
  ["0000000000000001", "000fffffffffffff", "0010000000000000"]
#guard project (cmp "ge" (literal "3ff0000000000000") ++ "," ++
    cmp "lt" (literal "3ff0000000000001")) ["3ff0000000000000"]

-- There is no implicit integer-to-float promotion in identity comparisons.
#guard project (cmp "eq" "{\"lit\":{\"u64\":0}}") []

-- Scalar and set parameters preserve float identity, including NaN.
#guard agrees (document "[{\"var\":0}]" (cmp "eq" "{\"param\":0}")
  "[{\"scalar\":{\"f64\":\"8000000000000001\"}}]" (rows ["8000000000000001"]))
#guard agrees (document "[{\"agg\":{\"op\":\"count\"}}]" ""
  "[{\"set\":[{\"f64\":\"0000000000000000\"},{\"f64\":\"7ff8000000000000\"}]}]"
  "[[{\"u64\":1}]]" "{\"param_set\":0}")

-- The one unbound rule assignment occurs once; repeated NaN facts cannot
-- multiply it. With a bound variable, two distinct float assignments count.
#guard agrees (document "[{\"agg\":{\"op\":\"count\"}}]"
  (cmp "eq" (literal "7ff8000000000000")) "[]" "[[{\"u64\":1}]]")
#guard agrees (document "[{\"agg\":{\"op\":\"count\"}}]"
  (cmp "ge" (literal "7ff0000000000000")) "[]" "[[{\"u64\":2}]]")

-- Min/max follow database total order rather than host NaN-elision rules.
#guard agrees (document
  "[{\"agg\":{\"op\":\"min\",\"over\":0}},{\"agg\":{\"op\":\"max\",\"over\":0}}]"
  "" "[]" "[[{\"f64\":\"fff0000000000000\"},{\"f64\":\"7ff8000000000000\"}]]")
#guard agrees (document
  "[{\"agg\":{\"op\":\"min\",\"over\":0}},{\"agg\":{\"op\":\"max\",\"over\":0}}]"
  (cmp "gt" (literal "fff0000000000000") ++ "," ++ cmp "lt" (literal "7ff0000000000000"))
  "[]" "[[{\"f64\":\"ffefffffffffffff\"},{\"f64\":\"7fefffffffffffff\"}]]")

-- No binding means no global aggregate group, not a fabricated zero row.
#guard agrees (document "[{\"agg\":{\"op\":\"count\"}}]"
  (cmp "eq" (literal "4000000000000000")) "[]" "[]")

end Bumbledb.Conformance.F64Boundary
