/* Generated by crates/bumbledb-node/dts.sh from the napi annotations. Do not edit. */

declare const handle: unique symbol

export interface ChangesCursorHandle {
  readonly [handle]: 'ChangesCursorHandle'
}

export interface ChangesHandle {
  readonly [handle]: 'ChangesHandle'
}

export interface CursorHandle {
  readonly [handle]: 'CursorHandle'
}

export interface DbHandle {
  readonly [handle]: 'DbHandle'
}

export interface DirectoryHandle {
  readonly [handle]: 'DirectoryHandle'
}

export interface DraftHandle {
  readonly [handle]: 'DraftHandle'
}

export interface OperationHandle {
  readonly [handle]: 'OperationHandle'
}

export interface PreparedHandle {
  readonly [handle]: 'PreparedHandle'
}

export interface QueryHandle {
  readonly [handle]: 'QueryHandle'
}

export interface ResultHandle {
  readonly [handle]: 'ResultHandle'
}

export interface RuntimeHandle {
  readonly [handle]: 'RuntimeHandle'
}

export interface SchemaHandle {
  readonly [handle]: 'SchemaHandle'
}

export interface SnapshotHandle {
  readonly [handle]: 'SnapshotHandle'
}

export interface T {
  readonly [handle]: 'T'
}


export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}

export interface AtomIn {
  source: AtomSourceIn
  bindings: Array<BindingIn>
}

export type AtomSourceIn =
  | { kind: 'Edb'; relation: number }
  | { kind: 'Interior'; interior: number }

export interface BindingIn {
  field: number
  term: TermIn
}

export type BoundSpecIn =
  | { kind: 'Lit'; value: string }
  | { kind: 'Field'; field: string }
  | { kind: 'Duration'; field: string }

export type CapacityWindowSpecIn =
  | { kind: 'Exact'; n: BoundSpecIn }
  | { kind: 'Range'; lo: BoundSpecIn; hi: BoundSpecIn }
  | { kind: 'Floor'; lo: BoundSpecIn }

/** A capacity ceiling; `Unbounded` is the `*` window end. */
export type CeilingOut =
  | { _tag: 'Unbounded' }
  | { _tag: 'Lit'; value: bigint }
  | { _tag: 'TargetField'; field: number }
  | { _tag: 'TargetDuration'; field: number }

export interface CellInterval {
  start: bigint | number
  end: bigint | number
}

/**
 * One row cell as JavaScript sees it: `u64`/`i64` as `bigint`, `f64` as
 * `number`, text and UUIDs as `string`, bytes as `Uint8Array`, intervals as
 * `{ start, end }` in their element's representation.
 */
export type CellValue = boolean | bigint | number | string | Uint8Array | CellInterval

export interface ChangeRecordWire {
  relation: number
  kind: string
  values: Array<CellValue>
}

/** One closed relation row: its handle, declaration-order id and columns. */
export interface ClosedRowOut {
  handle: string
  id: bigint
  values: Array<NamedValueOut>
}

export interface ClosedSpecIn {
  newtype: string
  rows: Array<RowSpecIn>
}

export interface CloseWire {
  kind: string
  outstanding?: InspectionWire
}

/** A comparison operator; `Allen.mask` is a nonzero 13-bit relation set. */
export type CmpOpIn =
  | { kind: 'Eq' }
  | { kind: 'Ne' }
  | { kind: 'Lt' }
  | { kind: 'Le' }
  | { kind: 'Gt' }
  | { kind: 'Ge' }
  | { kind: 'PointIn' }
  | { kind: 'Allen'; mask: number }

/** Compile one schema spec (the schema file's JSON) into a validated handle. */
export declare function compileSchema(specJson: string): SchemaCompiled

export type ConditionIn =
  | { kind: 'Leaf'; op: CmpOpIn; lhs: TermIn; rhs: TermIn }
  | { kind: 'And'; children: Array<ConditionIn> }
  | { kind: 'Or'; children: Array<ConditionIn> }

export declare function engineVersion(): string

export interface FieldOut {
  name: string
  id: number
  valueType: ValueTypeOut
  newtype?: string
}

export interface FieldSpecIn {
  name: string
  valueType: ValueTypeIn
  newtype?: string
}

export type FindTermIn =
  | { kind: 'Var'; var: number }
  | { kind: 'Compute'; expr: ScalarExprIn }
  | { kind: 'Segments'; op: SegmentOpIn; left: number; right: number }
  | { kind: 'Count' }
  | { kind: 'Aggregate'; op: FoldOpIn; over: number }
  | { kind: 'Pack'; over: number }

export type FixedIntervalElementIn = 'U64' | 'I64'

export type FoldOpIn = 'Sum' | 'Mean' | 'Min' | 'Max'

export type HeadOpIn = 'Sum' | 'Mean' | 'Min' | 'Max' | 'Count' | 'Pack'

export type HeadTermIn =
  | { kind: 'Var' }
  | { kind: 'Compute' }
  | { kind: 'Aggregate'; op: HeadOpIn }

export interface InspectionWire {
  phase: string
  queued: bigint
  active: bigint
  retained: bigint
  owners: bigint
  databases: bigint
  natives: bigint
}

export interface InteriorIn {
  rules: Array<RuleIn>
}

export type IntervalElementIn = 'U64' | 'I64' | 'F64'

export type IntervalElementOut = 'U64' | 'I64' | 'F64'

/** One selection binding's right side; a literal set reads disjunctively. */
export type LiteralSetSpecIn =
  | { kind: 'One'; literal: LiteralSpecIn }
  | { kind: 'Many'; literals: Array<LiteralSpecIn> }

/** A literal as spelled: a plain value, or a closed relation's handle. */
export type LiteralSpecIn =
  | { kind: 'Value'; value: ValueIn }
  | { kind: 'Handle'; handle: string }

/**
 * A JSON input that does not match its wire type: the serde path to the
 * offending node (for example `rules[0].atoms[2].bindings`) and why.
 */
export interface Malformed {
  path: string
  message: string
}

export interface NamedValueOut {
  name: string
  value: CellValue
}

export type NumericCastIn = 'ToF64' | 'ToF64Exact' | 'ToI64Exact' | 'ToU64Exact'

/**
 * The engine's refusal: its variant name, message, and whichever rule-local
 * coordinates it cites (`comparison` indexes the rule's flattened
 * comparisons).
 */
export interface QueryDiagnostic {
  code: string
  message: string
  rule?: number
  atom?: number
  find?: number
  field?: number
  relation?: number
  var?: number
  param?: number
  comparison?: number
  interior?: number
}

export interface QueryIn {
  interiors: Array<InteriorIn>
  head: Array<HeadTermIn>
  rules: Array<RuleIn>
  rec?: RecIn
}

export type QueryValidated =
  | { _tag: 'Valid'; query: ExternalObject<QueryHandle> }
  | { _tag: 'Invalid'; diagnostic: QueryDiagnostic }
  | { _tag: 'Malformed'; path: string; message: string }

/** A recursive stage: nonempty base and step arms. */
export interface RecIn {
  base: Array<RecRuleIn>
  rec: Array<RecStepIn>
}

export interface RecRuleIn {
  finds: Array<number>
  atoms: Array<AtomIn>
  conditions: Array<ConditionIn>
}

/** A recursive step: `selfBindings` binds the stage's own previous output. */
export interface RecStepIn {
  finds: Array<number>
  selfBindings: Array<BindingIn>
  atoms: Array<AtomIn>
  conditions: Array<ConditionIn>
}

export interface RelationOut {
  name: string
  id: number
  fields: Array<FieldOut>
  extension?: Array<ClosedRowOut>
}

/** One relation; `closed` present declares it closed. */
export interface RelationSpecIn {
  name: string
  fields: Array<FieldSpecIn>
  closed?: ClosedSpecIn
}

export type RoundingIn = 'TowardZero' | 'NearestTiesAwayFromZero' | 'NearestTiesToEven'

export interface RowSpecIn {
  handle: string
  values: Array<LiteralSpecIn>
}

export interface RuleIn {
  finds: Array<FindTermIn>
  atoms: Array<AtomIn>
  negated: Array<AtomIn>
  conditions: Array<ConditionIn>
}

export declare function runtimeApplyTake(handle: ExternalObject<OperationHandle>): object

/**
 * Arm the next `dispatch_payload_message` / `run_payload_publication`.
 * After `work()` returns a page and before `operation.output` is written,
 * the local owner is dropped and the job fails `Cancelled`. A page already
 * registered is kept. Predelivery `Err` still publishes nothing.
 */
export declare function runtimeArmPublicationCancel(handle: ExternalObject<RuntimeHandle>): void

export declare function runtimeBytesTake(handle: ExternalObject<OperationHandle>): Uint8Array

export declare function runtimeCancel(handle: ExternalObject<OperationHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeChangePageTake(handle: ExternalObject<OperationHandle>): Array<ChangeRecordWire> | null

export declare function runtimeChangesBytes(handle: ExternalObject<ChangesHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeChangesClose(handle: ExternalObject<ChangesHandle>, callback: (arg: CloseWire) => void): void

/**
 * Two routed borrows under one operation and cancellation context. The
 * first stage retains only an Arc, then returns its worker immediately.
 */
export declare function runtimeChangesCompose(left: ExternalObject<ChangesHandle>, right: ExternalObject<ChangesHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeChangesCursor(handle: ExternalObject<ChangesHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeChangesCursorClose(handle: ExternalObject<ChangesCursorHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeChangesCursorNext(handle: ExternalObject<ChangesCursorHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeChangesCursorTake(handle: ExternalObject<OperationHandle>): ExternalObject<ChangesCursorHandle>

export declare function runtimeChangesParse(handle: ExternalObject<RuntimeHandle>, schema: ExternalObject<SchemaHandle>, bytes: unknown, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeChangesTake(handle: ExternalObject<OperationHandle>): object

export declare function runtimeClose(handle: ExternalObject<RuntimeHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeCursorClose(handle: ExternalObject<CursorHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeCursorNext(handle: ExternalObject<CursorHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeCursorTake(handle: ExternalObject<OperationHandle>): ExternalObject<CursorHandle>

export declare function runtimeDbApply(db: ExternalObject<DbHandle>, changes: ExternalObject<ChangesHandle>, expected: object, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDbClearCache(db: ExternalObject<DbHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDbInspect(db: ExternalObject<DbHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDbInspectTake(handle: ExternalObject<OperationHandle>): object

export declare function runtimeDbJudge(db: ExternalObject<DbHandle>, changes: ExternalObject<ChangesHandle>, expected: object, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDbSnapshot(db: ExternalObject<DbHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDbTake(handle: ExternalObject<OperationHandle>): object

export declare function runtimeDecodeRows(handle: ExternalObject<RuntimeHandle>, schema: ExternalObject<SchemaHandle>, relation: number, bytes: unknown, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDirectoryAcquire(handle: ExternalObject<RuntimeHandle>, path: string, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDirectoryBegin(handle: ExternalObject<DirectoryHandle>): ExternalObject<OperationHandle>

export declare function runtimeDirectoryCheck(handle: ExternalObject<OperationHandle>): void

export declare function runtimeDirectoryClose(handle: ExternalObject<DirectoryHandle>, remove: boolean, callback: (arg: CloseWire) => void): void

/**
 * Open (or create) one database in a child directory of an owned
 * directory, under a compiled schema.
 */
export declare function runtimeDirectoryDbOpen(handle: ExternalObject<DirectoryHandle>, childName: string, schema: ExternalObject<SchemaHandle>, create: boolean, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDirectoryEnd(handle: ExternalObject<OperationHandle>): void

export declare function runtimeDirectoryTake(handle: ExternalObject<OperationHandle>): ExternalObject<DirectoryHandle>

export declare function runtimeDraftClose(handle: ExternalObject<DraftHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeDraftDelete(handle: ExternalObject<DraftHandle>, relation: number, rows: bigint, cells: unknown[], callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDraftFinish(handle: ExternalObject<DraftHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeDraftInsert(handle: ExternalObject<DraftHandle>, relation: number, rows: bigint, cells: unknown[], callback: () => void): ExternalObject<OperationHandle>

/** Open a database-free change draft under a compiled schema. */
export declare function runtimeDraftOpen(handle: ExternalObject<RuntimeHandle>, schema: ExternalObject<SchemaHandle>): ExternalObject<DraftHandle>

export declare function runtimeEncodeRows(handle: ExternalObject<RuntimeHandle>, schema: ExternalObject<SchemaHandle>, relation: number, rows: bigint, cells: unknown[], callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeErrorCodes(): Array<string>

export declare function runtimeInspect(handle: ExternalObject<RuntimeHandle>): InspectionWire

export declare function runtimeJudgeTake(handle: ExternalObject<OperationHandle>): object

export declare function runtimeManagedDbClose(db: ExternalObject<DbHandle>, callback: (arg: CloseWire) => void): void

/** Start the one live runtime. `optionsJson` is a `RuntimeOptionsIn`. */
export declare function runtimeOpen(optionsJson: string): ExternalObject<RuntimeHandle>

export interface RuntimeOptionsIn {
  workers?: number
  queueCapacity?: number
  cleanupCapacity?: number
  ownerCapacity?: number
  nativeHandleCapacity?: number
  cleanupTimeoutMs?: number
}

export declare function runtimePageTake(handle: ExternalObject<OperationHandle>): Array<Array<CellValue>> | null

export declare function runtimePreparedClose(handle: ExternalObject<PreparedHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimePreparedExecute(handle: ExternalObject<PreparedHandle>, params: unknown[], callback: () => void): ExternalObject<OperationHandle>

export declare function runtimePreparedReleaseMemory(handle: ExternalObject<PreparedHandle>, callback: () => void): ExternalObject<OperationHandle>

/**
 * Adopt one compiled worker-owned plan. Dropping an untaken output closes
 * the same resource; JavaScript is never its only cleanup authority.
 */
export declare function runtimePreparedTake(handle: ExternalObject<OperationHandle>): ExternalObject<PreparedHandle>

export declare function runtimeReady(handle: ExternalObject<RuntimeHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeReportTake(handle: ExternalObject<OperationHandle>): object

export declare function runtimeResultClose(handle: ExternalObject<ResultHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeResultCollect(handle: ExternalObject<ResultHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeResultCursor(handle: ExternalObject<ResultHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeResultTake(handle: ExternalObject<OperationHandle>): ExternalObject<ResultHandle>

export declare function runtimeRowsTake(handle: ExternalObject<OperationHandle>): Array<Array<CellValue>>

export declare function runtimeRowTake(handle: ExternalObject<OperationHandle>): Array<CellValue> | null

export declare function runtimeSnapshotClose(handle: ExternalObject<SnapshotHandle>, callback: (arg: CloseWire) => void): void

export declare function runtimeSnapshotExecute(handle: ExternalObject<SnapshotHandle>, query: ExternalObject<QueryHandle>, params: unknown[], callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeSnapshotGet(handle: ExternalObject<SnapshotHandle>, relation: number, keyStatement: number, keyValues: unknown[], callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeSnapshotPrepare(handle: ExternalObject<SnapshotHandle>, query: ExternalObject<QueryHandle>, callback: () => void): ExternalObject<OperationHandle>

export declare function runtimeSnapshotTake(handle: ExternalObject<OperationHandle>): object

/**
 * Take one completed operation's payload. PINNED double-take contract
 * (P12's F3 note, decided wave-E): the FIRST take spends the operation;
 * every later take of the same handle THROWS the typed `SpentHandle`
 * refusal — it never returns `null`. `null` is reserved for a payload-less
 * completion (`Output::Ready`), so silence can never be mistaken for a
 * spent handle. The same contract holds for every `*Take` verb riding
 * `Runtime::take` (db and log bridges included).
 */
export declare function runtimeTake(handle: ExternalObject<OperationHandle>): void

/** A scalar expression over rule-local variables. */
export type ScalarExprIn =
  | { kind: 'Var'; var: number }
  | { kind: 'Literal'; value: ValueIn }
  | { kind: 'Negate'; expr: ScalarExprIn }
  | { kind: 'Add'; left: ScalarExprIn; right: ScalarExprIn }
  | { kind: 'Subtract'; left: ScalarExprIn; right: ScalarExprIn }
  | { kind: 'Multiply'; left: ScalarExprIn; right: ScalarExprIn }
  | { kind: 'Divide'; left: ScalarExprIn; right: ScalarExprIn }
  | { kind: 'MulDiv'; a: ScalarExprIn; b: ScalarExprIn; divisor: ScalarExprIn; rounding: RoundingIn }
  | { kind: 'Measure'; expr: ScalarExprIn }
  | { kind: 'Cast'; cast: NumericCastIn; expr: ScalarExprIn }
  | { kind: 'IsNaN'; expr: ScalarExprIn }
  | { kind: 'IsFinite'; expr: ScalarExprIn }

/** TypeScript SDK declarations for a compiled schema. */
export declare function schemaBindings(schema: ExternalObject<SchemaHandle>): SchemaBindings

export type SchemaBindings =
  | { _tag: 'Bindings'; source: string }
  | { _tag: 'Unrepresentable'; coordinate: string; reason: string }

export type SchemaCompiled =
  | { _tag: 'Compiled'; schema: ExternalObject<SchemaHandle>; descriptor: SchemaDescriptorOut }
  | { _tag: 'Invalid'; diagnostic: SchemaDiagnostic }
  | { _tag: 'Malformed'; path: string; message: string }

/**
 * The sealed descriptor: relations with ids, field types and newtypes,
 * materialized statements, and the hex schema fingerprint.
 */
export interface SchemaDescriptorOut {
  relations: Array<RelationOut>
  statements: Array<StatementOut>
  fingerprint: string
}

/**
 * Why a spec did not compile: unresolved names (`Spec`), or a resolved
 * descriptor the engine refused (`Schema`, citing descriptor statement ids).
 */
export type SchemaDiagnostic =
  | { _tag: 'Spec'; issues: Array<SpecIssueOut> }
  | { _tag: 'Schema'; code: string; message: string; statement?: StatementCite; conflict?: StatementCite }

export interface SchemaSpecIn {
  relations: Array<RelationSpecIn>
  statements: Array<StatementSpecIn>
}

export type SegmentOpIn = 'Intersection' | 'Difference'

export interface SelectionIn {
  field: string
  set: LiteralSetSpecIn
}

export interface SelectionOut {
  field: number
  values: Array<CellValue>
}

export interface SideOut {
  relation: number
  projection: Array<number>
  selection: Array<SelectionOut>
}

/** One side of a containment or capacity statement, all by name. */
export interface SideSpecIn {
  relation: string
  projection: Array<string>
  selection: Array<SelectionIn>
}

/**
 * One spec resolution issue; `statement` indexes the spec's statements,
 * `relation` and `row` its relations and a closed relation's rows.
 */
export interface SpecIssueOut {
  code: string
  message: string
  statement?: number
  relation?: number
  row?: number
}

export interface StatementCite {
  id: number
  spelling: string
}

/** One materialized statement; `id` is its `StatementId`. */
export type StatementOut =
  | { _tag: 'Functionality'; id: number; spelling: string; relation: number; projection: Array<number> }
  | { _tag: 'Containment'; id: number; spelling: string; source: SideOut; target: SideOut }
  | { _tag: 'Capacity'; id: number; spelling: string; target: SideOut; weight: WeightOut; lo: bigint; hi: CeilingOut; source: SideOut }

/** One dependency statement; `bidirectional` containment is the `==` form. */
export type StatementSpecIn =
  | { kind: 'Fd'; relation: string; projection: Array<string> }
  | { kind: 'Containment'; source: SideSpecIn; target: SideSpecIn; bidirectional: boolean }
  | { kind: 'Capacity'; target: SideSpecIn; weight: WeightSpecIn; window: CapacityWindowSpecIn; source: SideSpecIn }

export type TermIn =
  | { kind: 'Var'; var: number }
  | { kind: 'Param'; param: number }
  | { kind: 'ParamSet'; param: number }
  | { kind: 'Literal'; value: ValueIn }

/** Validate one query IR (JSON) against a compiled schema. */
export declare function validateQuery(schema: ExternalObject<SchemaHandle>, irJson: string): QueryValidated

/** One literal value as spelled. Intervals are half-open and nonempty. */
export type ValueIn =
  | { kind: 'Bool'; value: boolean }
  | { kind: 'U64'; value: string }
  | { kind: 'I64'; value: string }
  | { kind: 'F64'; value: string }
  | { kind: 'String'; value: string }
  | { kind: 'Uuid'; value: string }
  | { kind: 'FixedBytes'; value: string }
  | { kind: 'IntervalU64'; start: string; end: string }
  | { kind: 'IntervalI64'; start: string; end: string }
  | { kind: 'IntervalF64'; start: string; end: string }

/** One structural field type. */
export type ValueTypeIn =
  | { kind: 'Bool' }
  | { kind: 'U64' }
  | { kind: 'I64' }
  | { kind: 'F64' }
  | { kind: 'String' }
  | { kind: 'Uuid' }
  | { kind: 'FixedBytes'; len: number }
  | { kind: 'Interval'; element: IntervalElementIn }
  | { kind: 'FixedInterval'; element: FixedIntervalElementIn; width: string }

export type ValueTypeOut =
  | { _tag: 'Bool' }
  | { _tag: 'U64' }
  | { _tag: 'I64' }
  | { _tag: 'F64' }
  | { _tag: 'String' }
  | { _tag: 'Uuid' }
  | { _tag: 'FixedBytes'; len: number }
  | { _tag: 'Interval'; element: IntervalElementOut }
  | { _tag: 'FixedInterval'; element: IntervalElementOut; width: bigint }

export type WeightOut =
  | { _tag: 'Unit' }
  | { _tag: 'Field'; field: number }
  | { _tag: 'Duration'; field: number }

export type WeightSpecIn =
  | { kind: 'Unit' }
  | { kind: 'Field'; field: string }
  | { kind: 'Duration'; field: string }
