/**
 * The primer-scale law-typing gate (PRD-K4's scale bar), runtime half. The
 * COMPILE half is the fixture itself: `test/fixtures/law-scale.ts`
 * (generated by `scripts/generate-law-scale.ts` — 40 relations, 200 field
 * slots, 123 statements inline in one `schema()` call) carries type-level
 * `Equal` pins that only compile if the class machinery computed the whole
 * map under default tsc limits. This file re-runs the same claims at the
 * VALUE tier — the runtime union-find over the identical fixture — and
 * pins the two tiers' agreement at scale.
 */

import assert from "node:assert/strict"
import { test } from "node:test"

import { LawScale, pinBare, pinChain, pinClosed, pinGenerator, pinVocab } from "#test/fixtures/law-scale.ts"

test("the primer-scale fixture constructs and both tiers agree at scale", function scaleGate() {
	// The compile-tier pins are VALUES — carrying them here re-asserts them at runtime.
	assert.ok(pinChain && pinVocab && pinGenerator && pinClosed && pinBare)

	assert.equal(Object.keys(LawScale.relations).length, 40, "40 relations")
	assert.equal(LawScale.statements.length, 123, "123 statements — statements in == statements out")
	let slots = 0
	for (const record of Object.values(LawScale.classes)) {
		slots += Object.keys(record).length
	}
	assert.equal(slots, 200, "200 field slots in the class map")

	// The runtime twins of the compile-tier spot pins.
	assert.equal(LawScale.classes.R5?.ref, "R4.id")
	assert.equal(LawScale.classes.R9?.kind, "Vocab1.id")
	assert.equal(LawScale.classes.R31?.id, "R31.id")
	assert.equal(LawScale.classes.Vocab7?.id, "Vocab7.id")
	assert.equal(LawScale.classes.R3?.score, undefined)

	// The generator-less interval bijections chain into one class named by
	// the least member in declaration order: R0.at leads the walk.
	assert.equal(LawScale.classes.R0?.at, "R0.at")
	assert.equal(LawScale.classes.R20?.at, "R0.at")
	assert.equal(LawScale.classes.R21?.at, "R0.at", "the pointwise composite containment joins the same chain")
})
