#!/usr/bin/env bash
# Generate ts/src/native/binding.d.ts from this crate's napi annotations with
# the napi-rs CLI type-def flow, branding every ExternalObject<T> payload.
#
#   crates/bumbledb-node/dts.sh             write ts/src/native/binding.d.ts
#   crates/bumbledb-node/dts.sh <file>      write <file>
#   crates/bumbledb-node/dts.sh --check     fail when the committed file is stale
set -euo pipefail
export PATH="$HOME/.cargo/bin:$PATH"
crate=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$crate/../.." && pwd)
committed="$repo/ts/src/native/binding.d.ts"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

printf '{"name":"bumbledb-native","private":true,"napi":{"binaryName":"bumbledb"}}\n' \
	>"$work/package.json"
pnpm --silent --package=@napi-rs/cli@3.10.8 dlx napi build \
	--manifest-path "$crate/Cargo.toml" \
	--package-json-path "$work/package.json" \
	--output-dir "$work" \
	--dts generated.d.ts \
	--no-const-enum \
	--no-dts-header >/dev/null

{
	printf '/* Generated by crates/bumbledb-node/dts.sh from the napi annotations. Do not edit. */\n\n'
	printf 'declare const handle: unique symbol\n\n'
	grep -o 'ExternalObject<[A-Za-z]*>' "$work/generated.d.ts" |
		sed 's/ExternalObject<\(.*\)>/\1/' | sort -u |
		while read -r name; do
			printf "export interface %s {\n  readonly [handle]: '%s'\n}\n\n" "$name" "$name"
		done
	cat "$work/generated.d.ts"
} >"$work/binding.d.ts"

case "${1:-}" in
--check) diff -u "$committed" "$work/binding.d.ts" ;;
"") cp "$work/binding.d.ts" "$committed" ;;
*) cp "$work/binding.d.ts" "$1" ;;
esac
